# Generated by Django 4.2.11 on 2024-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crusade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
                ('sababi', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
            options={
                'verbose_name': 'Crusade',
                'verbose_name_plural': 'crusade',
                'db_table': 'crusade',
                'ordering': ['sababi'],
            },
        ),
    ]
