# Generated by Django 4.2.11 on 2024-03-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheCrusades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crusade',
            options={'ordering': ['id'], 'verbose_name': 'Crusade', 'verbose_name_plural': 'crusade'},
        ),
    ]
